"""Generate the standard plots + per-record README for a record submission.

Usage:
    python make_record_report.py records/<dir> \
        [--wandb-runs entity/project/id1,entity/project/id2,...] \
        [--prev records/<previous-record-dir>]

Three plots: training (solve rate vs step + vs record-clock minutes), stability (grad
norm + loss), and eval (pass@k vs the target line).

Artifact-only mode needs nothing beyond the committed record directory
(train_log_seed*.txt + eval_seed*.json): it parses the per-step record-clock lines and
the args attestation straight from the run logs, so any reviewer can regenerate the
plots from the PR alone. --wandb-runs swaps the training panel to the unbiased online
solve-rate metric from W&B history; if your metrics live elsewhere, anything that yields
(step, online_solved_frac) can be adapted — see fetch_wandb_history for the expected shape.

The record README is written with the human-authored sections preserved: everything
between the AUTO markers is regenerated, everything outside them is never touched.
On first run a scaffold with a TODO "Idea" section is created.

Run via:  uv run --with matplotlib --with pandas [--with wandb] python make_record_report.py ...
"""

from __future__ import annotations

import argparse
import glob
import json
import math
import re
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.patheffects as pe  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
from matplotlib.ticker import PercentFormatter  # noqa: E402

AUTO_BEGIN = "<!-- BEGIN AUTO-GENERATED by make_record_report.py — edits inside will be overwritten -->"
AUTO_END = "<!-- END AUTO-GENERATED -->"
STEP_RE = re.compile(
    r"step:(\d+)/(\d+) record_time:([\d.]+)s step_avg:[\d.]+s reward_mean:([\d.]+) "
    r"solved_frac:([\d.]+) loss:(-?[\d.]+) grad_norm:([\d.]+)"
    r"(?: cum_flops:([\d.eE+-]+))?"  # node-invariant FLOPs-to-target (logs predating it omit it)
)
# Key hyperparameters surfaced in the README config table; the full args dict goes in <details>.
HEADLINE_ARGS = [
    "learning_rate", "lr_schedule", "min_lr_frac", "lr_decay_steps", "warmup_steps",
    "cispo_eps", "loss_normalization", "examples_per_step", "num_samples",
    "max_new_tokens", "temperature", "top_p", "max_staleness", "inflight_requests",
    "interruption", "interrupt_answer_tokens", "max_steps", "seed",
]
# --- Dark "dashboard" theme -------------------------------------------------
# One opaque look that renders identically on GitHub (light *and* dark) and in
# the X/Twitter feed. Backgrounds are baked into every PNG — never transparent —
# so dark axes and text can't vanish when the host page is also dark.
BG = "#0d1117"        # figure canvas (GitHub-dark)
PANEL = "#161b22"     # axes face: a lighter card on the canvas adds depth
INK = "#e6edf3"       # primary text / foreground
MUTED = "#8b949e"     # secondary text: subtitles, ticks, captions
GRID = "#30363d"      # hairline grid
TARGET_C = "#ff7b72"  # target / threshold lines (warm coral)
SEED_COLORS = ["#22d3ee", "#fbbf24", "#a78bfa"]  # cyan / amber / violet — pop on dark
DASH = (0, (5, 4))    # shared dashed style for reference lines
SMOOTH = 8            # rolling window for the bold trend line


def set_house_style() -> None:
    """Bake the dark dashboard look into rcParams. Call once before plotting.

    Fonts and line weights run deliberately heavy: in-feed images on X render
    small and get JPEG-recompressed, so thin pale strokes turn to mush.
    """
    plt.rcParams.update({
        "figure.facecolor": BG, "savefig.facecolor": BG, "axes.facecolor": PANEL,
        "figure.dpi": 130, "savefig.dpi": 200, "savefig.bbox": "tight",
        "figure.constrained_layout.use": True,
        "font.size": 13, "text.color": INK,
        "axes.titlesize": 15, "axes.titleweight": "bold",
        "axes.titlelocation": "left", "axes.titlecolor": INK,
        "axes.labelsize": 12, "axes.labelcolor": MUTED,
        "axes.edgecolor": GRID, "axes.linewidth": 1.0,
        "axes.spines.top": False, "axes.spines.right": False,
        "axes.grid": True, "axes.grid.axis": "y",
        "grid.color": GRID, "grid.alpha": 0.55, "grid.linewidth": 0.8,
        "xtick.color": MUTED, "ytick.color": MUTED,
        "xtick.labelsize": 11, "ytick.labelsize": 11,
        "legend.frameon": False, "legend.labelcolor": INK, "legend.fontsize": 11,
        "lines.linewidth": 2.6, "lines.solid_capstyle": "round",
    })


def glow(line, lw: float = 8.0, alpha: float = 0.28) -> None:
    """Lay a soft, wide stroke of the line's own color behind it — neon under-glow."""
    line.set_path_effects([pe.Stroke(linewidth=lw, foreground=line.get_color(), alpha=alpha),
                           pe.Normal()])


def first_cross(x, y, target: float) -> float | None:
    """First x-value at which series y reaches `target` (None if it never does)."""
    xa, ya = np.asarray(x, float), np.asarray(y, float)
    hit = np.flatnonzero(ya >= target)
    return float(xa[hit[0]]) if hit.size else None


def fmt_clock(seconds: float) -> str:
    s = int(seconds)
    h, m, sec = s // 3600, s % 3600 // 60, s % 60
    return f"{h}:{m:02d}:{sec:02d}" if h else f"{m}:{sec:02d}"


def pct_axis(ax) -> None:
    ax.yaxis.set_major_formatter(PercentFormatter(xmax=1.0, decimals=0))


def smooth(s):
    """Rolling-mean trend line; min_periods=1 so the early steps still render."""
    return s.rolling(SMOOTH, min_periods=1).mean()


def target_line(ax, value: float, label: str, color: str = TARGET_C) -> None:
    """Dashed horizontal reference + a left-anchored label (blended transform so
    the label hugs the left spine regardless of the x-scale)."""
    ax.axhline(value, color=color, ls=DASH, lw=1.6, alpha=0.9)
    ax.annotate(label, xy=(0.012, value), xycoords=ax.get_yaxis_transform(),
                xytext=(0, 5), textcoords="offset points",
                color=color, fontsize=11, fontweight="bold")


def draw_speedrun(ax, df, color: str, target: float, annotate: bool = True) -> float | None:
    """The signature panel: smoothed solve-rate vs record clock with a raw ghost
    underneath, gradient fill, neon glow, and the target-crossing marker.
    Returns the wall-clock minute the smoothed curve first hits `target`."""
    x = df.record_time_s / 60.0
    sm = smooth(df.solved_frac)
    ax.plot(x, df.solved_frac, color=color, alpha=0.10, lw=1.0)
    glow(ax.plot(x, sm, color=color, alpha=0.97)[0], lw=9, alpha=0.32)
    ax.fill_between(x, sm, color=color, alpha=0.12)
    xc = first_cross(x, sm, target)
    if xc is not None:
        ax.scatter([xc], [target], s=90, color=color, zorder=7, edgecolor=BG, linewidth=2)
        if annotate:
            ax.annotate(f"target reached\n@ {xc:.0f} min", xy=(xc, target),
                        xytext=(-12, 16), textcoords="offset points", ha="right", va="bottom",
                        color=INK, fontsize=13, fontweight="bold")
    return xc


def fmt_flops(f: float | None) -> str:
    """Human-readable FLOPs-to-target (the node-invariant leaderboard metric)."""
    if f is None or not (isinstance(f, (int, float)) and math.isfinite(f)) or f <= 0:
        return "—"
    return f"{f / 1e18:.3f} EFLOP"


def parse_train_log(path: Path) -> dict:
    """Extract the per-step record-clock series and the args attestation from a run log."""
    steps, args_dict = [], None
    for line in path.read_text(errors="replace").splitlines():
        m = STEP_RE.match(line)
        if m:
            steps.append({
                "step": int(m.group(1)), "record_time_s": float(m.group(3)),
                "reward_mean": float(m.group(4)), "solved_frac": float(m.group(5)),
                "loss": float(m.group(6)), "grad_norm": float(m.group(7)),
                "cum_flops": float(m.group(8)) if m.group(8) else float("nan"),
            })
        elif line.startswith("args: {") and args_dict is None:
            # The attestation prints repr(vars(args)); PosixPath is its only non-literal.
            args_dict = eval(  # noqa: S307 — sandboxed: no builtins, PosixPath -> str
                line[len("args: "):], {"__builtins__": {}}, {"PosixPath": lambda p: p})
        elif line.startswith("final_checkpoint:"):
            m2 = re.search(r"record_time:([\d.]+)s", line)
            if m2 and steps:
                steps[-1]["final_record_time_s"] = float(m2.group(1))
            mf = re.search(r"cum_flops:([\d.eE+-]+)", line)
            if mf and steps:
                steps[-1]["cum_flops"] = float(mf.group(1))
    if not steps:
        raise ValueError(f"{path}: no step lines found")
    df = pd.DataFrame(steps)
    final_time = steps[-1].get("final_record_time_s", df.record_time_s.iloc[-1])
    final_flops = steps[-1].get("cum_flops", df.cum_flops.iloc[-1])
    # Records whose log predates cum_flops can carry a `<log_stem>.flops.txt` sidecar with the
    # FLOPs-to-target reconstructed from W&B (per-step perf_est/total_flops summed to target).
    if not (isinstance(final_flops, float) and math.isfinite(final_flops)):
        sidecar = path.with_suffix(".flops.txt")
        if sidecar.exists():
            final_flops = float(sidecar.read_text().split()[0])
    return {"df": df, "args": args_dict or {}, "final_time_s": final_time,
            "final_flops": final_flops}


def load_record(record_dir: Path) -> dict:
    logs, evals = {}, {}
    for p in sorted(record_dir.glob("train_log_seed*.txt")):
        if p.name.endswith(".flops.txt"):
            continue  # FLOPs sidecar, read by parse_train_log; not a log itself
        logs[p.stem.replace("train_log_", "")] = parse_train_log(p)
    for p in sorted(record_dir.glob("eval_seed*.json")):
        evals[p.stem.replace("eval_", "").split(".")[0]] = json.loads(p.read_text())
    if not logs or not evals:
        raise SystemExit(f"{record_dir}: need train_log_seed*.txt and eval_seed*.json")
    return {"logs": logs, "evals": evals, "name": record_dir.name}


def fetch_wandb_history(run_paths: list[str]) -> list[pd.DataFrame]:
    """One DataFrame per run with step + online-solve columns."""
    import wandb
    api = wandb.Api()
    frames = []
    for rp in run_paths:
        # Full history rather than scan_history(keys=...): keyed scans drop rows missing
        # any requested key, which silently empties the result for sparse metrics.
        df = api.run(rp).history(samples=100_000, pandas=True)
        if "step" not in df.columns:
            raise SystemExit(f"{rp}: no 'step' metric in W&B history")
        frames.append(df[df["step"].notna()].sort_values("step"))
    return frames


def plot_training(record: dict, wandb_frames: list[pd.DataFrame] | None, out: Path,
                  target: float = 0.80) -> None:
    """Solve rate vs step and vs record-clock minutes; W&B's unbiased online metric
    when available. Raw ghost + bold rolling mean, gradient fill, and the moment
    the curve crosses the target."""
    fig, axes = plt.subplots(1, 2, figsize=(13, 4.8))
    multi = len(record["logs"]) > 1
    src = "online solve rate" if wandb_frames is not None else "trained-batch solve rate"
    ymax, clock_crossings = 0.0, []
    for i, (seed, log) in enumerate(record["logs"].items()):
        df, c = log["df"], SEED_COLORS[i % len(SEED_COLORS)]
        if wandb_frames is not None:
            w = wandb_frames[i]
            n = min(len(w), len(df))
            raw = w["reward/online_solved_frac_unfiltered"].iloc[:n].reset_index(drop=True)
            xstep = w["step"].iloc[:n].reset_index(drop=True)
            xclock = (df.record_time_s.iloc[:n] / 60.0).reset_index(drop=True)
        else:
            raw, xstep, xclock = df.solved_frac, df.step, df.record_time_s / 60.0
        sm = smooth(raw)
        ymax = max(ymax, float(sm.max()))
        for ax, x, is_clock in ((axes[0], xstep, False), (axes[1], xclock, True)):
            ax.plot(x, raw, color=c, alpha=0.10, lw=1.0)
            glow(ax.plot(x, sm, color=c, alpha=0.96, label=seed)[0], lw=8, alpha=0.28)
            ax.fill_between(x, sm, color=c, alpha=0.11)
            xc = first_cross(x, sm, target)
            if xc is not None:
                ax.scatter([xc], [target], s=64, color=c, zorder=7, edgecolor=BG, linewidth=1.6)
                if is_clock:
                    clock_crossings.append(xc)
    for ax in axes:
        target_line(ax, target, f"TARGET {target:g}")
        ax.set_ylim(0, max(ymax, target) * 1.12); pct_axis(ax)
        ax.set_ylabel(src)
        if multi:
            ax.legend(loc="lower right")
    axes[0].set_xlabel("training step")
    axes[0].set_title(f"Training curve  ·  {SMOOTH}-step rolling mean")
    axes[1].set_xlabel("record clock (minutes)")
    axes[1].set_title("The speedrun view  ·  solve rate vs wall clock")
    if clock_crossings:
        xc = min(clock_crossings)
        axes[1].annotate(f"target reached @ {xc:.0f} min", xy=(xc, target),
                         xytext=(-10, 16), textcoords="offset points", ha="right",
                         color=INK, fontsize=12, fontweight="bold")
    fig.savefig(out); plt.close(fig)


def plot_stability(record: dict, out: Path) -> None:
    """Grad norm (pre-clip, log) with the clip threshold drawn in; loss with a
    bold rolling mean over its raw ghost."""
    fig, axes = plt.subplots(1, 2, figsize=(13, 4.4))
    multi, clip = len(record["logs"]) > 1, None
    for i, (seed, log) in enumerate(record["logs"].items()):
        df, c = log["df"], SEED_COLORS[i % len(SEED_COLORS)]
        glow(axes[0].plot(df.step, df.grad_norm, color=c, alpha=0.9, label=seed)[0], lw=6, alpha=0.16)
        axes[1].plot(df.step, df.loss, color=c, alpha=0.20, lw=1.2)
        glow(axes[1].plot(df.step, smooth(df.loss),
                          color=c, alpha=0.96, label=seed)[0], lw=6, alpha=0.16)
        clip = clip if clip is not None else log["args"].get("grad_clip")
    if clip is not None:
        target_line(axes[0], float(clip), f"clip {float(clip):g}")
    axes[0].set_yscale("log"); axes[0].set_title("Gradient norm  ·  pre-clip")
    axes[1].set_title("Loss")
    for ax in axes:
        ax.set_xlabel("training step")
        if multi:
            ax.legend(loc="best")
    fig.savefig(out); plt.close(fig)


def plot_eval(record: dict, target: float, out: Path) -> None:
    """pass@k curve with the bootstrap CI on pass@1 and the capability band above
    target — the capability-expansion view."""
    evals = record["evals"]
    multi = len(evals) > 1
    fig, ax = plt.subplots(figsize=(9, 5.2))
    ks = [1]
    for i, (seed, ev) in enumerate(evals.items()):
        c = SEED_COLORS[i % len(SEED_COLORS)]
        ks = sorted(int(k) for k in ev["pass_at_k"])
        ys = [ev["pass_at_k"][str(k)] for k in ks]
        ax.fill_between(ks, ys, target, color=c, alpha=0.07)
        glow(ax.plot(ks, ys, "o-", color=c, ms=9, label=seed, zorder=5)[0], lw=7, alpha=0.22)
        lo, hi = ev.get("ci_low"), ev.get("ci_high")
        if lo is not None and hi is not None:
            ax.errorbar([1], [ev["pass_at_1"]], yerr=[[ev["pass_at_1"] - lo], [hi - ev["pass_at_1"]]],
                        color=c, capsize=5, lw=2.2, zorder=6)
        for k, y in zip(ks, ys):
            ax.annotate(f"{y:.0%}", (k, y), xytext=(0, 11), textcoords="offset points",
                        ha="center", color=INK, fontsize=11, fontweight="bold")
    target_line(ax, target, f"TARGET {target:g}")
    ax.set_xscale("log", base=2); ax.set_xticks(ks, [str(k) for k in ks])
    ax.set_xlabel("k (samples per puzzle)"); ax.set_ylabel("pass@k")
    pct_axis(ax); ax.set_ylim(max(0.0, target - 0.1), 1.06)
    ax.set_title("Capability  ·  pass@k vs target")
    if multi:
        ax.legend(loc="lower right")
    fig.savefig(out); plt.close(fig)


def plot_hero_card(record: dict, target: float, out: Path) -> None:
    """Clean 16:9 record card: training climb, record time, pass@1, target."""
    logs, evals = record["logs"], record["evals"]
    fig = plt.figure(figsize=(12.8, 7.2), constrained_layout=False)
    gs = fig.add_gridspec(1, 2, width_ratios=[1.5, 1.0],
                          left=0.065, right=0.965, top=0.80, bottom=0.13, wspace=0.11)
    ax_main = fig.add_subplot(gs[0, 0])
    ax_card = fig.add_subplot(gs[0, 1]); ax_card.axis("off")

    fig.text(0.065, 0.925, "Sokoban Speedrun", fontsize=36, fontweight="bold",
             color=INK, ha="left", va="center")

    for i, log in enumerate(logs.values()):
        df = log["df"]
        x = df.record_time_s / 60.0
        y = smooth(df.solved_frac)
        color = SEED_COLORS[i % len(SEED_COLORS)]
        ax_main.plot(x, df.solved_frac, color=color, alpha=0.10, lw=1.0)
        glow(ax_main.plot(x, y, color=color, alpha=0.97)[0], lw=9, alpha=0.28)
        ax_main.fill_between(x, y, color=color, alpha=0.12)
        ax_main.scatter([x.iloc[-1]], [y.iloc[-1]], s=72, color=color, zorder=7,
                        edgecolor=BG, linewidth=1.8)
    smax = max(float(smooth(l["df"].solved_frac).max()) for l in logs.values())
    ax_main.set_ylim(0.32, max(0.78, smax * 1.08)); pct_axis(ax_main)
    ax_main.set_xlabel("minutes"); ax_main.set_ylabel("train solve rate")
    ax_main.set_title("")

    final_time = logs[sorted(logs)[0]]["final_time_s"]
    p1s = [e["pass_at_1"] for e in evals.values()]
    p1 = sum(p1s) / len(p1s)

    ax_card.text(0.0, 0.82, "RECORD", color=MUTED, fontsize=17,
                 fontweight="bold", va="top")
    ax_card.text(0.0, 0.72, fmt_clock(final_time), color=INK, fontsize=52,
                 fontweight="bold", va="top")
    ax_card.text(0.0, 0.45, "PASS@1", color=MUTED, fontsize=17,
                 fontweight="bold", va="top")
    ax_card.text(0.0, 0.36, f"{p1:.1%}", color=SEED_COLORS[0], fontsize=78,
                 fontweight="bold", va="top")
    ax_card.text(0.0, 0.12, f"target > {target:.0%}", color=TARGET_C, fontsize=22,
                 fontweight="bold", va="top")
    fig.savefig(out); plt.close(fig)


def verification_block(record_dir: Path, target: float) -> list[str]:
    """Render the ## Verification section from a nested verification/ mini-record, if present.

    verification/ is itself a record dir — an independent rerun (train_log_seed*.txt +
    eval_seed*.json + rollouts) plus an optional one-line verifier.txt (e.g. '@maintainer  PR#12'
    or 'Self-verified by the maintainers'). The verdict is derived from the eval JSON, so it can
    never drift from the committed artifacts; `verify_record.py records/<dir>` re-scores it too."""
    vdir = record_dir / "verification"
    vevals = sorted(vdir.glob("eval_seed*.json")) if vdir.is_dir() else []
    if not vevals:
        return []
    att = vdir / "verifier.txt"
    who = (att.read_text().strip().splitlines()[0].strip()
           if att.exists() and att.read_text().strip() else "Verifier unrecorded")
    lines = ["## Verification", "", f"{who}:", ""]
    for p in vevals:
        ev = json.loads(p.read_text())
        seed = p.stem.replace("eval_", "").split(".")[0]
        clears = ev["ci_low"] > target
        commit = ev.get("git_commit")
        commit_txt = f", recipe commit `{commit[:10]}`" if commit else ""
        lines.append(
            f"- re-ran at {seed}{commit_txt} → pass@1 **{ev['pass_at_1']:.4f}** "
            f"(95% CI [{ev['ci_low']:.4f}, {ev['ci_high']:.4f}]) — "
            f"**{'CLEARS' if clears else 'DOES NOT CLEAR'} {target}** {'✓' if clears else '✗'}")
    lines += ["", "Confirms the recipe reproduces independently; the record time above is the "
              "submission run's, not this rerun's. Artifacts: [`verification/`](verification/).", ""]
    return lines


def auto_block(record: dict, record_dir: Path, target: float, prev_dir: Path | None) -> str:
    evals, logs = record["evals"], record["logs"]
    clocks = {s: logs[s]["final_time_s"] for s in sorted(logs)}
    flops = {s: logs[s].get("final_flops") for s in sorted(logs)}
    lines = ["## Results", "", "| seed | pass@1 | 95% CI | record clock | FLOPs |",
             "|---|---|---|---|---|"]
    for s in sorted(evals):
        ev, clock, fl = evals[s], clocks.get(s), flops.get(s)
        hms = f"{int(clock // 3600)}:{int(clock % 3600 // 60):02d}:{int(clock % 60):02d}" if clock else "—"
        flo = fmt_flops(fl)
        lines.append(f"| {s} | {ev['pass_at_1']:.4f} | [{ev['ci_low']:.4f}, {ev['ci_high']:.4f}] "
                     f"| {hms} | {flo} |")
    # Single-seed gate: each run independently clears the target via its lower 95% bootstrap CI
    # (no cross-seed averaging — see the leaderboard rules).
    if len(evals) == 1:
        only = evals[sorted(evals)[0]]
        verdict = "CLEARS" if only["ci_low"] > target else "DOES NOT CLEAR"
        summary = (f"**pass@1 {only['pass_at_1']:.4f}, lower 95% CI {only['ci_low']:.4f} vs "
                   f"TARGET {target}: {verdict}.**")
    else:
        all_clear = all(ev["ci_low"] > target for ev in evals.values())
        summary = (f"**Each of {len(evals)} runs vs TARGET {target} by its lower 95% CI: "
                   f"{'ALL CLEAR' if all_clear else 'NOT ALL CLEAR'}.**")
    lines += ["", summary, "",
              "![hero](plots/hero.png)", "",
              "![training](plots/training.png)", "",
              "<details><summary>diagnostic plots</summary>", "",
              "![stability](plots/stability.png)", "",
              "![eval](plots/eval.png)", "",
              "</details>", ""]
    lines += verification_block(record_dir, target)
    # Config: headline table + diff vs previous record + full dict.
    args = logs[sorted(logs)[0]]["args"]
    lines += ["## Config", "", "| arg | value |", "|---|---|"]
    lines += [f"| `{k}` | `{args[k]}` |" for k in HEADLINE_ARGS if k in args]
    if prev_dir is not None:
        prev_logs = sorted(prev_dir.glob("train_log_seed*.txt"))
        if prev_logs:
            prev_args = parse_train_log(prev_logs[0])["args"]
            diffs = [(k, prev_args.get(k, "—"), args[k]) for k in sorted(args)
                     if k != "run" and str(args[k]) != str(prev_args.get(k))]
            if diffs:
                lines += ["", f"**Changed vs [{prev_dir.name}](../{prev_dir.name}/):**", "",
                          "| arg | before | after |", "|---|---|---|"]
                lines += [f"| `{k}` | `{b}` | `{a}` |" for k, b, a in diffs]
    full = json.dumps({k: str(v) for k, v in sorted(args.items())}, indent=2)
    lines += ["", "<details><summary>full args</summary>", "", "```json", full, "```", "</details>", ""]
    lines += ["## Reproduce", "", "```bash",
              "# train (recipe defaults live in speedrun.py RECIPE + modal_app.py)",
              "MAX_STEPS=<steps> RUN_NAME=<run> modal run --detach modal_app.py",
              "# eval the final checkpoint under the leaderboard protocol, then verify offline",
              "EVAL_CHECKPOINT=/vol/outputs/<run>/step_<final> modal run modal_app.py",
              f"python verify_record.py records/{record_dir.name}", "```", ""]
    return "\n".join(lines)


def write_readme(record_dir: Path, block: str) -> None:
    readme = record_dir / "README.md"
    auto = f"{AUTO_BEGIN}\n\n{block}\n{AUTO_END}\n"
    if readme.exists():
        text = readme.read_text()
        if AUTO_BEGIN in text and AUTO_END in text:
            pre, rest = text.split(AUTO_BEGIN, 1)
            _, post = rest.split(AUTO_END, 1)
            readme.write_text(pre + auto + post)
            return
        readme.write_text(text.rstrip() + "\n\n" + auto)
        return
    title = record_dir.name
    readme.write_text(
        f"# {title}\n\n## Idea\n\nTODO: describe the recipe — what changed vs the previous "
        f"record, why it should be faster, and anything a reader should know before "
        f"trusting/forking it.\n\n{auto}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("record_dir", type=Path)
    ap.add_argument("--wandb-runs", default=None,
                    help="comma-separated entity/project/run_id list, one per seed, ordered like the seed files")
    ap.add_argument("--prev", type=Path, default=None, help="previous record dir for the config diff")
    ap.add_argument("--target", type=float, default=0.80)
    args = ap.parse_args()

    set_house_style()
    record = load_record(args.record_dir)
    plots = args.record_dir / "plots"
    plots.mkdir(exist_ok=True)

    wandb_frames = None
    if args.wandb_runs:
        wandb_frames = fetch_wandb_history([r.strip() for r in args.wandb_runs.split(",")])
    plot_training(record, wandb_frames, plots / "training.png", args.target)
    plot_stability(record, plots / "stability.png")
    plot_eval(record, args.target, plots / "eval.png")
    plot_hero_card(record, args.target, plots / "hero.png")

    write_readme(args.record_dir,
                 auto_block(record, args.record_dir, args.target, args.prev))
    print(f"wrote {plots}/*.png (incl. hero.png) and updated {args.record_dir / 'README.md'}")


if __name__ == "__main__":
    main()
