"""Generate the standard plots + per-record README for a record submission.

Usage:
    python ../make_record_report.py records/<dir> \
        [--wandb-runs entity/project/id1,entity/project/id2,...] \
        [--prev records/<previous-record-dir>]

    # regenerate the README world-record figures (assets/*.png) from the
    # leaderboard tables — run after editing a leaderboard row, no record dir:
    python make_record_report.py --leaderboard

Three plots: training (solve rate vs step + vs record-clock minutes), stability (grad
norm + loss), and eval (pass@k vs the target line).

Artifact-only mode needs nothing beyond the committed record directory
(train_log_seed*.txt + eval_seed*.json): it parses the per-step record-clock lines and
the args attestation straight from the run logs, so any reviewer can regenerate the
plots from the PR alone. --wandb-runs fetches the train solve-rate metric from W&B;
if your metrics live elsewhere, anything that yields
(step, online_solved_frac) can be adapted — see fetch_wandb_history for the expected shape.

The record README is written with the human-authored sections preserved: everything
between the AUTO markers is regenerated, everything outside them is never touched.
On first run a scaffold with a TODO "Idea" section is created.

Run from a track directory via:
    uv run python ../make_record_report.py ...
"""

from __future__ import annotations

import argparse
import glob
import hashlib
import json
import math
import re
from pathlib import Path
from urllib.parse import urlparse

import matplotlib

matplotlib.use("Agg")
import matplotlib.patheffects as pe  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
from matplotlib.ticker import PercentFormatter  # noqa: E402

AUTO_BEGIN = "<!-- BEGIN AUTO-GENERATED by make_record_report.py — edits inside will be overwritten -->"
AUTO_END = "<!-- END AUTO-GENERATED -->"
REPO_ROOT = Path(__file__).resolve().parent
SOURCE_DIVIDER = "=" * 100
STEP_RE = re.compile(
    r"step:(\d+)/(\d+) record_time:([\d.]+)s step_avg:[\d.]+s reward_mean:([\d.]+) "
    r"solved_frac:([\d.]+) loss:(-?[\d.]+) grad_norm:([\d.]+)"
    r"(?: cum_flops:([\d.eE+-]+))?"  # node-invariant FLOPs-to-target (logs predating it omit it)
)
# Key hyperparameters surfaced in the README config table; the full args dict goes in <details>.
HEADLINE_ARGS = [
    "learning_rate", "lr_schedule", "min_lr_frac", "lr_decay_steps", "warmup_steps",
    "cispo_eps", "loss_normalization", "adv_centered_blend", "adv_difficulty_weight",
    "adv_difficulty_ramp", "adv_variance_boost", "examples_per_step", "num_samples",
    "max_new_tokens", "temperature", "top_p", "max_staleness", "inflight_requests",
    "interruption", "interrupt_answer_tokens", "max_steps", "seed",
]
# --- Dark "dashboard" theme -------------------------------------------------
# One opaque look that renders identically on GitHub (light *and* dark) and in
# the X/Twitter feed. Backgrounds are baked into every PNG — never transparent —
# so dark axes and text can't vanish when the host page is also dark.
BG = "#0d1117"        # figure canvas (GitHub-dark)
PANEL = "#161b22"     # axes face: a lighter card on the canvas adds depth
INK = "#e6edf3"       # primary text / foreground
MUTED = "#8b949e"     # secondary text: subtitles, ticks, captions
GRID = "#30363d"      # hairline grid
TARGET_C = "#ff7b72"  # target / threshold lines (warm coral)
SEED_COLORS = ["#22d3ee", "#fbbf24", "#a78bfa"]  # cyan / amber / violet — pop on dark
DASH = (0, (5, 4))    # shared dashed style for reference lines
SMOOTH = 8            # rolling window for the bold trend line
ONLINE_METRIC = "reward/online_solved_frac_unfiltered"
ONLINE_METRIC_ALIASES = (ONLINE_METRIC, "online_solved_frac", "online_solve_rate")
ONLINE_TRAIN_LABEL = "train solve rate"
FILTERED_TRAIN_LABEL = "filtered accepted-train diagnostic"


def set_house_style() -> None:
    """Bake the dark dashboard look into rcParams. Call once before plotting.

    Fonts and line weights run deliberately heavy: in-feed images on X render
    small and get JPEG-recompressed, so thin pale strokes turn to mush.
    """
    plt.rcParams.update({
        "figure.facecolor": BG, "savefig.facecolor": BG, "axes.facecolor": PANEL,
        "figure.dpi": 130, "savefig.dpi": 200, "savefig.bbox": "tight",
        "figure.constrained_layout.use": True,
        "font.size": 13, "text.color": INK,
        "axes.titlesize": 15, "axes.titleweight": "bold",
        "axes.titlelocation": "left", "axes.titlecolor": INK,
        "axes.labelsize": 12, "axes.labelcolor": MUTED,
        "axes.edgecolor": GRID, "axes.linewidth": 1.0,
        "axes.spines.top": False, "axes.spines.right": False,
        "axes.grid": True, "axes.grid.axis": "y",
        "grid.color": GRID, "grid.alpha": 0.55, "grid.linewidth": 0.8,
        "xtick.color": MUTED, "ytick.color": MUTED,
        "xtick.labelsize": 11, "ytick.labelsize": 11,
        "legend.frameon": False, "legend.labelcolor": INK, "legend.fontsize": 11,
        "lines.linewidth": 2.6, "lines.solid_capstyle": "round",
    })


def glow(line, lw: float = 8.0, alpha: float = 0.28) -> None:
    """Lay a soft, wide stroke of the line's own color behind it — neon under-glow."""
    line.set_path_effects([pe.Stroke(linewidth=lw, foreground=line.get_color(), alpha=alpha),
                           pe.Normal()])


def first_cross(x, y, target: float) -> float | None:
    """First x-value at which series y reaches `target` (None if it never does)."""
    xa, ya = np.asarray(x, float), np.asarray(y, float)
    hit = np.flatnonzero(ya >= target)
    return float(xa[hit[0]]) if hit.size else None


def fmt_clock(seconds: float) -> str:
    """mm:ss — runs are assumed under an hour for now."""
    s = int(seconds)
    return f"{s // 60}:{s % 60:02d}"


def pct_axis(ax) -> None:
    ax.yaxis.set_major_formatter(PercentFormatter(xmax=1.0, decimals=0))


def smooth(s):
    """Rolling-mean trend line; min_periods=1 so the early steps still render."""
    return s.rolling(SMOOTH, min_periods=1).mean()


def normalize_wandb_run(run_path: str) -> str:
    """Accept either entity/project/run_id or a wandb.ai run URL."""
    run_path = run_path.strip()
    if not run_path.startswith(("http://", "https://")):
        return run_path.strip("/")
    parsed = urlparse(run_path)
    parts = [p for p in parsed.path.split("/") if p]
    if len(parts) >= 4 and parts[2] == "runs":
        return f"{parts[0]}/{parts[1]}/{parts[3]}"
    raise SystemExit(f"could not parse W&B run URL: {run_path}")


def online_metric_col(df: pd.DataFrame) -> str:
    for col in ONLINE_METRIC_ALIASES:
        if col in df.columns:
            return col
    raise SystemExit(
        f"online metric history needs one of {', '.join(ONLINE_METRIC_ALIASES)}"
    )


def normalize_online_frame(df: pd.DataFrame) -> pd.DataFrame:
    if "step" not in df.columns:
        raise SystemExit("online metric history needs a step column")
    col = online_metric_col(df)
    out = df[["step", col]].dropna().rename(columns={col: ONLINE_METRIC}).copy()
    out["step"] = out["step"].astype(int)
    out[ONLINE_METRIC] = out[ONLINE_METRIC].astype(float)
    return out.sort_values("step").drop_duplicates("step", keep="last").reset_index(drop=True)


def aligned_training_series(log: dict, online_frame: pd.DataFrame | None = None) -> dict:
    """Return x/y vectors for the training plot and a precise metric label."""
    df = log["df"]
    if online_frame is None:
        return {
            "raw": df.solved_frac.reset_index(drop=True),
            "xstep": df.step.reset_index(drop=True),
            "xclock": (df.record_time_s / 60.0).reset_index(drop=True),
            "label": FILTERED_TRAIN_LABEL,
            "source": "filtered",
        }

    w = normalize_online_frame(online_frame)
    log_by_step = df.set_index("step")["record_time_s"]
    step_values = w["step"].astype(int)
    if step_values.add(1).isin(log_by_step.index).all():
        # W&B logs the loop's zero-based step; RunLogger prints one-based step:N/total.
        plot_step = step_values + 1
    elif step_values.isin(log_by_step.index).all():
        plot_step = step_values
    else:
        n = min(len(w), len(df))
        w = w.iloc[:n].reset_index(drop=True)
        return {
            "raw": w[ONLINE_METRIC],
            "xstep": df.step.iloc[:n].reset_index(drop=True),
            "xclock": (df.record_time_s.iloc[:n] / 60.0).reset_index(drop=True),
            "label": ONLINE_TRAIN_LABEL,
            "source": "online",
        }

    return {
        "raw": w[ONLINE_METRIC].reset_index(drop=True),
        "xstep": plot_step.reset_index(drop=True),
        "xclock": (plot_step.map(log_by_step) / 60.0).reset_index(drop=True),
        "label": ONLINE_TRAIN_LABEL,
        "source": "online",
    }


def target_line(ax, value: float, label: str, color: str = TARGET_C) -> None:
    """Dashed horizontal reference + a left-anchored label (blended transform so
    the label hugs the left spine regardless of the x-scale)."""
    ax.axhline(value, color=color, ls=DASH, lw=1.6, alpha=0.9)
    ax.annotate(label, xy=(0.012, value), xycoords=ax.get_yaxis_transform(),
                xytext=(0, 5), textcoords="offset points",
                color=color, fontsize=11, fontweight="bold")


def draw_speedrun(ax, df, color: str, target: float, annotate: bool = True) -> float | None:
    """The signature panel: smoothed solve-rate vs record clock with a raw ghost
    underneath, gradient fill, neon glow, and the target-crossing marker.
    Returns the wall-clock minute the smoothed curve first hits `target`."""
    x = df.record_time_s / 60.0
    sm = smooth(df.solved_frac)
    ax.plot(x, df.solved_frac, color=color, alpha=0.10, lw=1.0)
    glow(ax.plot(x, sm, color=color, alpha=0.97)[0], lw=9, alpha=0.32)
    ax.fill_between(x, sm, color=color, alpha=0.12)
    xc = first_cross(x, sm, target)
    if xc is not None:
        ax.scatter([xc], [target], s=90, color=color, zorder=7, edgecolor=BG, linewidth=2)
        if annotate:
            ax.annotate(f"target reached\n@ {xc:.0f} min", xy=(xc, target),
                        xytext=(-12, 16), textcoords="offset points", ha="right", va="bottom",
                        color=INK, fontsize=13, fontweight="bold")
    return xc


def fmt_flops(f: float | None) -> str:
    """Raw FLOPs-to-target (the node-invariant leaderboard metric).

    Reported as the exact FLOP count in scientific notation (matching the ``.6e``
    cum_flops format in the train logs) rather than rounded to ``EFLOP``: this is a
    speedrun metric where small gaps decide records, so no unit-rounding."""
    if f is None or not (isinstance(f, (int, float)) and math.isfinite(f)) or f <= 0:
        return "—"
    return f"{f:.6e}"


def train_log_paths(record_dir: Path) -> list[Path]:
    return [
        p for p in sorted(record_dir.glob("train_log_seed*.txt"))
        if not p.name.endswith(".flops.txt")
    ]


def extract_speedrun_source_from_log(path: Path) -> str:
    text = path.read_text(encoding="utf-8", errors="replace")
    source, sep, _rest = text.partition(f"\n{SOURCE_DIVIDER}\n")
    if not sep:
        raise ValueError(f"{path}: could not find run-log source divider")
    if source.startswith("<source unavailable:"):
        raise ValueError(f"{path}: embedded speedrun.py source is unavailable")
    return source if source.endswith("\n") else source + "\n"


def source_snapshot_path(record_dir: Path, seed: str) -> Path:
    return record_dir / "source" / f"speedrun_{seed}.py"


def ensure_source_snapshots(record_dir: Path) -> list[dict]:
    """Ensure source/speedrun_<seed>.py exists and matches the source embedded in each log."""
    rows = []
    for log_path in train_log_paths(record_dir):
        seed = log_path.stem.replace("train_log_", "")
        dest = source_snapshot_path(record_dir, seed)
        embedded = extract_speedrun_source_from_log(log_path)
        if not dest.exists():
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(embedded, encoding="utf-8")
        snapshot = dest.read_text(encoding="utf-8")
        if snapshot != embedded:
            raise SystemExit(f"{dest}: does not match source embedded in {log_path}")
        sha = hashlib.sha256(snapshot.encode("utf-8")).hexdigest()
        rows.append({"seed": seed, "path": dest, "sha256": sha})
    return rows


def ensure_all_source_snapshots(record_dir: Path) -> list[dict]:
    rows = [{"run": "submission", **row} for row in ensure_source_snapshots(record_dir)]
    verification_dir = record_dir / "verification"
    if verification_dir.is_dir():
        rows.extend({"run": "verification", **row} for row in ensure_source_snapshots(verification_dir))
    return rows


def parse_train_log(path: Path) -> dict:
    """Extract the per-step record-clock series and the args attestation from a run log."""
    steps, args_dict = [], None
    for line in path.read_text(errors="replace").splitlines():
        m = STEP_RE.match(line)
        if m:
            steps.append({
                "step": int(m.group(1)), "record_time_s": float(m.group(3)),
                "reward_mean": float(m.group(4)), "solved_frac": float(m.group(5)),
                "loss": float(m.group(6)), "grad_norm": float(m.group(7)),
                "cum_flops": float(m.group(8)) if m.group(8) else float("nan"),
            })
        elif line.startswith("args: {") and args_dict is None:
            # The attestation prints repr(vars(args)); PosixPath is its only non-literal.
            args_dict = eval(  # noqa: S307 — sandboxed: no builtins, PosixPath -> str
                line[len("args: "):], {"__builtins__": {}}, {"PosixPath": lambda p: p})
        elif line.startswith("final_checkpoint:"):
            m2 = re.search(r"record_time:([\d.]+)s", line)
            if m2 and steps:
                steps[-1]["final_record_time_s"] = float(m2.group(1))
            mf = re.search(r"cum_flops:([\d.eE+-]+)", line)
            if mf and steps:
                steps[-1]["cum_flops"] = float(mf.group(1))
    if not steps:
        raise ValueError(f"{path}: no step lines found")
    df = pd.DataFrame(steps)
    final_time = steps[-1].get("final_record_time_s", df.record_time_s.iloc[-1])
    final_flops = steps[-1].get("cum_flops", df.cum_flops.iloc[-1])
    # Records whose log predates cum_flops can carry a `<log_stem>.flops.txt` sidecar with the
    # FLOPs-to-target reconstructed from W&B (per-step perf_est/total_flops summed to target).
    if not (isinstance(final_flops, float) and math.isfinite(final_flops)):
        sidecar = path.with_suffix(".flops.txt")
        if sidecar.exists():
            final_flops = float(sidecar.read_text().split()[0])
    return {"df": df, "args": args_dict or {}, "final_time_s": final_time,
            "final_flops": final_flops}


def load_record(record_dir: Path) -> dict:
    logs, evals = {}, {}
    for p in train_log_paths(record_dir):
        logs[p.stem.replace("train_log_", "")] = parse_train_log(p)
    for p in sorted(record_dir.glob("eval_seed*.json")):
        evals[p.stem.replace("eval_", "").split(".")[0]] = json.loads(p.read_text())
    if not logs or not evals:
        raise SystemExit(f"{record_dir}: need train_log_seed*.txt and eval_seed*.json")
    return {"logs": logs, "evals": evals, "name": record_dir.name}


def load_metrics_frames(record_dir: Path, seeds: list[str]) -> list[pd.DataFrame] | None:
    """Per-seed metrics_seed<seed>.jsonl written by speedrun.py's RunLogger — the offline
    stand-in for fetch_wandb_history (record runs are --no-wandb). All-or-nothing: every
    seed log must have its metrics file, else fall back to the filtered step: lines."""
    paths = [record_dir / f"metrics_{seed}.jsonl" for seed in seeds]
    if not paths or not all(p.exists() for p in paths):
        return None
    return [normalize_online_frame(pd.read_json(p, lines=True)) for p in paths]


def fetch_wandb_history(run_paths: list[str]) -> list[pd.DataFrame]:
    """One normalized DataFrame per run with step + train solve rate."""
    import wandb
    api = wandb.Api()
    frames = []
    for rp in run_paths:
        rp = normalize_wandb_run(rp)
        # Full history rather than scan_history(keys=...): keyed scans drop rows missing
        # any requested key, which silently empties the result for sparse metrics.
        df = api.run(rp).history(samples=100_000, pandas=True)
        frames.append(normalize_online_frame(df))
    return frames


def plot_training(record: dict, online_frames: list[pd.DataFrame] | None, out: Path,
                  target: float = 0.80) -> None:
    """Solve rate vs record-clock minutes.

    Prefer the train metric from W&B/history artifacts. The leaderboard
    target is intentionally omitted here: the target gate is held-out eval CI, not a
    train-curve threshold.
    """
    fig, ax = plt.subplots(figsize=(9.2, 5.0))
    multi = len(record["logs"]) > 1
    src, ymax = ONLINE_TRAIN_LABEL if online_frames is not None else FILTERED_TRAIN_LABEL, 0.0
    for i, (seed, log) in enumerate(record["logs"].items()):
        c = SEED_COLORS[i % len(SEED_COLORS)]
        series = aligned_training_series(log, online_frames[i] if online_frames is not None else None)
        raw, xclock = series["raw"], series["xclock"]
        sm = smooth(raw)
        ymax = max(ymax, float(sm.max()))
        ax.plot(xclock, raw, color=c, alpha=0.10, lw=1.0)
        glow(ax.plot(xclock, sm, color=c, alpha=0.96, label=seed)[0], lw=8, alpha=0.28)
        ax.fill_between(xclock, sm, color=c, alpha=0.11)
    ax.set_ylim(0, max(ymax, target) * 1.12); pct_axis(ax)
    ax.set_xlabel("record clock (minutes)")
    ax.set_ylabel(src)
    ax.set_title(f"Train solve rate vs record clock  ·  {SMOOTH}-step rolling mean")
    if multi:
        ax.legend(loc="lower right")
    fig.savefig(out); plt.close(fig)


def plot_stability(record: dict, out: Path) -> None:
    """Grad norm (pre-clip, log) with the clip threshold drawn in; loss with a
    bold rolling mean over its raw ghost."""
    fig, axes = plt.subplots(1, 2, figsize=(13, 4.4))
    multi, clip = len(record["logs"]) > 1, None
    for i, (seed, log) in enumerate(record["logs"].items()):
        df, c = log["df"], SEED_COLORS[i % len(SEED_COLORS)]
        glow(axes[0].plot(df.step, df.grad_norm, color=c, alpha=0.9, label=seed)[0], lw=6, alpha=0.16)
        axes[1].plot(df.step, df.loss, color=c, alpha=0.20, lw=1.2)
        glow(axes[1].plot(df.step, smooth(df.loss),
                          color=c, alpha=0.96, label=seed)[0], lw=6, alpha=0.16)
        clip = clip if clip is not None else log["args"].get("grad_clip")
    if clip is not None:
        target_line(axes[0], float(clip), f"clip {float(clip):g}")
    axes[0].set_yscale("log"); axes[0].set_title("Gradient norm  ·  pre-clip")
    axes[1].set_title("Loss")
    for ax in axes:
        ax.set_xlabel("training step")
        if multi:
            ax.legend(loc="best")
    fig.savefig(out); plt.close(fig)


def plot_eval(record: dict, target: float, out: Path) -> None:
    """pass@k curve with the bootstrap CI on pass@1 and the capability band above
    target — the capability-expansion view."""
    evals = record["evals"]
    multi = len(evals) > 1
    fig, ax = plt.subplots(figsize=(9, 5.2))
    ks = [1]
    for i, (seed, ev) in enumerate(evals.items()):
        c = SEED_COLORS[i % len(SEED_COLORS)]
        ks = sorted(int(k) for k in ev["pass_at_k"])
        ys = [ev["pass_at_k"][str(k)] for k in ks]
        ax.fill_between(ks, ys, target, color=c, alpha=0.07)
        glow(ax.plot(ks, ys, "o-", color=c, ms=9, label=seed, zorder=5)[0], lw=7, alpha=0.22)
        lo, hi = ev.get("ci_low"), ev.get("ci_high")
        if lo is not None and hi is not None:
            ax.errorbar([1], [ev["pass_at_1"]], yerr=[[ev["pass_at_1"] - lo], [hi - ev["pass_at_1"]]],
                        color=c, capsize=5, lw=2.2, zorder=6)
        for k, y in zip(ks, ys):
            ax.annotate(f"{y:.0%}", (k, y), xytext=(0, 11), textcoords="offset points",
                        ha="center", color=INK, fontsize=11, fontweight="bold")
    target_line(ax, target, f"TARGET {target:g}")
    ax.set_xscale("log", base=2); ax.set_xticks(ks, [str(k) for k in ks])
    ax.set_xlabel("k (samples per puzzle)"); ax.set_ylabel("pass@k")
    pct_axis(ax); ax.set_ylim(max(0.0, target - 0.1), 1.06)
    ax.set_title("Capability  ·  pass@k vs target")
    if multi:
        ax.legend(loc="lower right")
    fig.savefig(out); plt.close(fig)


def plot_hero_card(record: dict, target: float, out: Path,
                   online_frames: list[pd.DataFrame] | None = None, subtitle: str = "") -> None:
    """Clean 16:9 record card: training climb, record time, pass@1, target."""
    logs, evals = record["logs"], record["evals"]
    fig = plt.figure(figsize=(12.8, 7.2), constrained_layout=False)
    gs = fig.add_gridspec(1, 2, width_ratios=[1.5, 1.0],
                          left=0.065, right=0.965, top=0.80, bottom=0.13, wspace=0.11)
    ax_main = fig.add_subplot(gs[0, 0])
    ax_card = fig.add_subplot(gs[0, 1]); ax_card.axis("off")

    fig.text(0.065, 0.93, "Sokoban Speedrun", fontsize=36, fontweight="bold",
             color=INK, ha="left", va="center")
    if subtitle:
        fig.text(0.066, 0.872, subtitle, fontsize=15, fontweight="bold",
                 color=MUTED, ha="left", va="center")

    smax = 0.0
    source = "filtered"
    for i, log in enumerate(logs.values()):
        series = aligned_training_series(log, online_frames[i] if online_frames is not None else None)
        x, raw_y = series["xclock"], series["raw"]
        y = smooth(raw_y)
        smax = max(smax, float(y.max()))
        source = series["source"]
        color = SEED_COLORS[i % len(SEED_COLORS)]
        ax_main.plot(x, raw_y, color=color, alpha=0.10, lw=1.0)
        glow(ax_main.plot(x, y, color=color, alpha=0.97)[0], lw=9, alpha=0.28)
        ax_main.fill_between(x, y, color=color, alpha=0.12)
        ax_main.scatter([x.iloc[-1]], [y.iloc[-1]], s=72, color=color, zorder=7,
                        edgecolor=BG, linewidth=1.8)
    ax_main.set_ylim(0.32, max(0.78, smax * 1.08)); pct_axis(ax_main)
    ax_main.set_xlabel("minutes")
    ax_main.set_ylabel(ONLINE_TRAIN_LABEL if source == "online" else FILTERED_TRAIN_LABEL)
    ax_main.set_title("")

    final_time = logs[sorted(logs)[0]]["final_time_s"]
    p1s = [e["pass_at_1"] for e in evals.values()]
    p1 = sum(p1s) / len(p1s)

    ax_card.text(0.0, 0.82, "RECORD", color=MUTED, fontsize=17,
                 fontweight="bold", va="top")
    ax_card.text(0.0, 0.72, fmt_clock(final_time), color=INK, fontsize=52,
                 fontweight="bold", va="top")
    ax_card.text(0.0, 0.45, "HELD-OUT PASS@1", color=MUTED, fontsize=17,
                 fontweight="bold", va="top")
    ax_card.text(0.0, 0.36, f"{p1:.1%}", color=SEED_COLORS[0], fontsize=78,
                 fontweight="bold", va="top")
    ax_card.text(0.0, 0.12, f"lower CI > {target:.0%}", color=TARGET_C, fontsize=22,
                 fontweight="bold", va="top")
    fig.savefig(out); plt.close(fig)


def verification_block(record_dir: Path, target: float) -> list[str]:
    """Render the ## Verification section from a nested verification/ mini-record, if present.

    verification/ is itself a record dir — an independent rerun (train_log_seed*.txt +
    eval_seed*.json + rollouts) plus an optional one-line verifier.txt (e.g. '@maintainer  PR#12'
    or 'Self-verified by the maintainers'). The verdict is derived from the eval JSON, so it can
    never drift from the committed artifacts; the track verifier re-scores it too."""
    vdir = record_dir / "verification"
    vevals = sorted(vdir.glob("eval_seed*.json")) if vdir.is_dir() else []
    if not vevals:
        return []
    att = vdir / "verifier.txt"
    who = (att.read_text().strip().splitlines()[0].strip()
           if att.exists() and att.read_text().strip() else "Verifier unrecorded")
    lines = ["## Verification", "", f"{who}:", ""]
    for p in vevals:
        ev = json.loads(p.read_text())
        seed = p.stem.replace("eval_", "").split(".")[0]
        clears = ev["ci_low"] > target
        commit = ev.get("git_commit")
        commit_txt = f", recipe commit `{commit[:10]}`" if commit else ""
        lines.append(
            f"- re-ran at {seed}{commit_txt} → pass@1 **{ev['pass_at_1']:.4f}** "
            f"(95% CI [{ev['ci_low']:.4f}, {ev['ci_high']:.4f}]) — "
            f"**{'CLEARS' if clears else 'DOES NOT CLEAR'} {target}** {'✓' if clears else '✗'}")
    lines += ["", "Confirms the recipe reproduces independently; the record time above is the "
              "submission run's, not this rerun's. Artifacts: [`verification/`](verification/).", ""]
    return lines


# Track-specific strings for the auto-generated Source + Reproduce blocks (records are first-class for
# both the LLM and non-LLM tracks; `--track` selects the right script + commands).
TRACKS = {
    "llm": {
        "target": 0.80,
        "script": "speedrun.py",
        "show_flops": False,
        "lb_section": "LLM Track",          # README world-record table heading
        "lb_title": "Sokoban Speedrun  ·  LLM Track",
        "lb_metric": "Held-out pass@1",
        "lb_out": "assets/llm_records.png",
        "reproduce": [
            "# train on one 8xH100 node (the recipe is baked into speedrun.py's RECIPE — no recipe flags)",
            "NODE_GPUS=8 uv run torchrun --standalone --nproc_per_node=3 -m speedrun -- "
            "--run <run> --seed <seed> --no-wandb --no-save-rollouts --final-rollout-steps 0",
            "# eval the final checkpoint under the leaderboard protocol, then verify offline",
            "uv run python -m eval_speedrun --run <run>-final-eval "
            "--eval-checkpoint outputs/<run>/step_<final> --eval-k 8 --eval-seed 12345 "
            "--eval-limit 0 --eval-max-tokens 12288 --eval-max-model-len 16384 "
            "--eval-interruption --eval-interrupt-answer-tokens 512 --eval-vllm-dp 8 "
            "--eval-gpu-mem-util 0.9 --eval-vllm-max-num-batched-tokens 40960 "
            "--eval-vllm-max-num-seqs 32 --eval-concurrency 32",
        ],
        "verify": ["uv run python verify_record.py {record}"],
    },
    "non-llm": {
        "target": 0.70,
        "script": "speedrun.py",
        "show_flops": False,   # open-architecture track: a FLOPs estimator can't stay faithful across archs
        "lb_section": "Non-LLM Track",      # README world-record table heading
        "lb_title": "Sokoban Speedrun  ·  Non-LLM Track",
        "lb_metric": "Held-out solve rate",
        "lb_out": "assets/non_llm_records.png",
        "reproduce": [
            "# train (the record recipe is baked into speedrun.py's RECIPE — no recipe flags or env needed)",
            "RUN_NAME=<run> uv run modal run --detach modal_app_non_llm.py",
            "# eval the final checkpoint (model config comes from RECIPE too)",
            "EVAL_CHECKPOINT=/vol/outputs/<run>/final.pt uv run modal run modal_app_non_llm.py",
            "# verify offline (re-derives pass@1/CI + checks the eval bin); maintainers also rerun at a 2nd seed",
        ],
        "verify": ["uv run python verify_record.py {record}"],
    },
}


# --- Leaderboard figure (README world-record tables -> assets/*.png) ---------
# One light, academic plot per track: each accepted record is a point at
# (wall-clock time to target, held-out accuracy), with the fixed target dashed.
# Faster is right, more accurate is up, so successive records march toward the
# top-right — the same spirit as modded-nanoGPT's `figure_wr_vs_base`. The data is
# read straight from the README leaderboard tables, so the figure fills in as
# faster records land. Regenerate after editing a row: `--leaderboard`.
LB_INK = "#1b1f24"      # titles / record labels
LB_MUTED = "#333a42"    # axis labels, ticks (darkened for feed contrast)
LB_GRID = "#d3d7dd"     # grid (darker so it survives X's downscale + re-encode)
LB_ACCENT = "#2563a8"   # superseded records (deep academic blue)
LB_RECORD = "#d4a017"   # current (fastest clearing) record — gold star
LB_TARGET = "#c0392b"   # target threshold (warm red, dashed)


def _lb_minutes(time_str: str) -> float:
    """'48:53' (mm:ss) -> minutes — runs are assumed under an hour for now."""
    m, sec = (int(p) for p in time_str.split(":"))
    return m + sec / 60.0


def parse_leaderboard(section: str) -> list[dict]:
    """Pull one track's record rows (num, minutes, held-out acc) from its README table."""
    text = (REPO_ROOT / "README.md").read_text()
    block = next(s for s in re.split(r"^## ", text, flags=re.M) if s.startswith(section))
    out = []
    for line in block.splitlines():
        if not re.match(r"\|\s*\d+\s*\|", line):  # a data row: leading | <int> |
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        out.append({
            "num": int(cells[0]),
            "minutes": _lb_minutes(cells[1]),
            "acc": float(re.search(r"[\d.]+", cells[5]).group()),
        })
    return sorted(out, key=lambda r: r["num"])


def set_leaderboard_style() -> None:
    """Light academic theme on white — distinct from the dark record-plot house style."""
    plt.rcParams.update({
        "figure.facecolor": "white", "savefig.facecolor": "white", "axes.facecolor": "white",
        "figure.dpi": 130, "savefig.dpi": 200, "savefig.bbox": "tight",
        "font.size": 15, "text.color": LB_INK,
        "axes.titlesize": 20, "axes.titleweight": "bold",
        "axes.titlelocation": "left", "axes.titlecolor": LB_INK, "axes.titlepad": 14,
        "axes.labelsize": 16, "axes.labelcolor": LB_MUTED,
        "axes.edgecolor": "#b7bcc4", "axes.linewidth": 1.2,
        "axes.spines.top": False, "axes.spines.right": False,
        "axes.grid": True, "axes.grid.axis": "y",
        "grid.color": LB_GRID, "grid.linewidth": 1.1,
        "xtick.color": LB_MUTED, "ytick.color": LB_MUTED,
        "xtick.labelsize": 14, "ytick.labelsize": 14,
        "legend.frameon": False, "legend.fontsize": 12, "legend.labelcolor": LB_INK,
        "lines.solid_capstyle": "round",
    })


def plot_leaderboard(cfg: dict) -> None:
    recs = parse_leaderboard(cfg["lb_section"])
    out = REPO_ROOT / cfg["lb_out"]
    if not recs:
        print(f"no records under '{cfg['lb_section']}' in README — skipped {out.name}")
        return
    target, accs = cfg["target"], [r["acc"] for r in recs]
    best = min(range(len(recs)), key=lambda i: recs[i]["minutes"])
    x_max = max(r["minutes"] for r in recs)

    fig, ax = plt.subplots(figsize=(7.8, 4.7))
    ax.set_title(cfg["lb_title"])
    # target near the bottom (thin "below target" strip), records near the top
    # only a little headroom past the slowest record — keep the left whitespace tight
    ax.set_xlim(x_max * 1.08, 0)
    ax.set_ylim(max(0.0, target - 0.02), min(1.0, max(accs) + 0.025))

    ax.axhspan(ax.get_ylim()[0], target, color=LB_TARGET, alpha=0.05, zorder=0)
    ax.axhline(target, color=LB_TARGET, lw=2.2, ls=(0, (6, 4)), zorder=2)
    ax.annotate(f"target {target:.0%}", xy=(0.985, target), xycoords=ax.get_yaxis_transform(),
                xytext=(0, 6), textcoords="offset points", va="bottom", ha="right",
                color=LB_TARGET, fontsize=13, fontweight="bold")

    # connect successive records (only meaningful with >= 2); each clears the target
    order = sorted(range(len(recs)), key=lambda i: recs[i]["num"])
    if len(recs) > 1:
        ax.plot([recs[i]["minutes"] for i in order], [recs[i]["acc"] for i in order],
                color=LB_ACCENT, lw=1.8, alpha=0.5, zorder=3)

    for i, r in enumerate(recs):
        if i == best:
            ax.scatter([r["minutes"]], [r["acc"]], marker="*", s=560, color=LB_RECORD,
                       edgecolors=LB_INK, linewidths=1.0, zorder=6)
            dx = 26
        else:
            ax.scatter([r["minutes"]], [r["acc"]], s=120, color=LB_ACCENT,
                       edgecolors="white", linewidths=1.2, zorder=5)
            dx = 15
        ax.annotate(f"#{r['num']}", xy=(r["minutes"], r["acc"]), xytext=(dx, 0),
                    textcoords="offset points", ha="left", va="center",
                    color=LB_INK, fontsize=15, fontweight="bold")

    ax.set_xlabel("wall-clock minutes to target")
    ax.set_ylabel(cfg["lb_metric"])
    pct_axis(ax)
    ax.margins(x=0)
    fig.tight_layout()
    out.parent.mkdir(exist_ok=True)
    fig.savefig(out)
    plt.close(fig)
    print(f"wrote {out.relative_to(REPO_ROOT)}  ({len(recs)} record(s))")


def make_leaderboard() -> None:
    """Regenerate every track's world-record figure from the README tables."""
    set_leaderboard_style()
    for track in TRACKS:
        plot_leaderboard(TRACKS[track])


def _track_path_prefix(track: str) -> str:
    """Repo-relative dir for a track ('llm' / 'non_llm') — note the TRACKS key is 'non-llm'."""
    return "non_llm" if track == "non-llm" else "llm"


def update_leaderboard_row(record_dir: Path, track: str) -> None:
    """Insert (or refresh) this record's row in the README world-record table, then redraw the
    figures. The derived columns (record time, date, log link, pass@1/CI) are read from the
    record's own artifacts; Description and Contributors are human-authored, so a new row gets
    placeholders to fill in and an existing row keeps whatever is already there."""
    rec = load_record(record_dir)
    seed = sorted(rec["logs"])[0]
    s = int(rec["logs"][seed]["final_time_s"])
    clock = fmt_clock(s)  # mm:ss (both tracks' headers)
    # Report the WORST of the required seeds (submission run + verification rerun), not the
    # submission seed alone. Both seeds must clear the bar, so the binding (lower) one is the
    # honest, un-cherry-pickable quality signal — it stops a submitter from seed-shopping the
    # headline. The *ranking* is still wall-clock (the submission run's clock, set above).
    eval_paths = sorted(record_dir.glob("eval_seed*.json")) + \
        sorted((record_dir / "verification").glob("eval_seed*.json"))
    ev = min((json.loads(p.read_text()) for p in eval_paths), key=lambda e: e["pass_at_1"])
    acc = f"{ev['pass_at_1']:.3f} (CI [{ev['ci_low']:.2f}, {ev['ci_high']:.2f}])"

    name = record_dir.name                                     # e.g. 2026-06-29_01_grpo
    m = re.match(r"(\d{4}-\d{2}-\d{2})_(\d+)", name)
    date = m.group(1) if m else "<date>"
    label = f"{m.group(1)}_{m.group(2)}" if m else name        # 2026-06-29_01 (drops the name suffix)
    prefix = _track_path_prefix(track)
    link = f"[{prefix}/records/{label}]({prefix}/records/{name}/)"

    section = TRACKS[track]["lb_section"]                       # "LLM Track" / "Non-LLM Track"
    readme = REPO_ROOT / "README.md"
    lines = readme.read_text().splitlines()

    # The section's data rows run from its `## <section>` heading to the next `## ` heading.
    start = next((i for i, ln in enumerate(lines) if ln.strip() == f"## {section}"), None)
    if start is None:
        raise SystemExit(f"README.md has no '## {section}' section to update")
    end = next((i for i in range(start + 1, len(lines)) if lines[i].startswith("## ")), len(lines))
    data_rows = [i for i in range(start, end) if re.match(r"\|\s*\d+\s*\|", lines[i])]
    cells = lambda i: [c.strip() for c in lines[i].strip().strip("|").split("|")]

    existing = next((i for i in data_rows if name in cells(i)[4]), None)
    if existing is not None:
        c = cells(existing)
        new = [c[0], clock, c[2], date, link, acc, c[6]]       # keep human-authored Description + Contributors
        if new == c:
            print(f"leaderboard: row #{c[0]} for {name} already current")
        else:
            lines[existing] = "| " + " | ".join(new) + " |"
            print(f"leaderboard: refreshed row #{c[0]} for {name}")
    else:
        num = max((int(cells(i)[0]) for i in data_rows), default=0) + 1
        desc, contrib = "<describe: algorithm, key hparams, steps>", "@you"
        row = f"| {num} | {clock} | {desc} | {date} | {link} | {acc} | {contrib} |"
        after = data_rows[-1] if data_rows else next(
            i for i in range(start, end) if re.match(r"\|\s*-+\s*\|", lines[i]))
        lines.insert(after + 1, row)
        print(f"leaderboard: added row #{num} for {name} — fill in Description + Contributors in README.md")

    readme.write_text("\n".join(lines) + "\n")
    make_leaderboard()


def source_block(record_dir: Path, source_rows: list[dict], script: str = "speedrun.py") -> list[str]:
    if not source_rows:
        return []
    lines = [
        "## Source",
        "",
        f"Standalone `{script}` snapshots are saved per run and checked against the embedded run-log source.",
        "",
        "| run | seed | snapshot | sha256 |",
        "|---|---|---|---|",
    ]
    for row in source_rows:
        rel = row["path"].relative_to(record_dir).as_posix()
        lines.append(
            f"| {row['run']} | {row['seed']} | [{rel}]({rel}) | `{row['sha256'][:12]}` |"
        )
    lines.append("")
    return lines


def auto_block(record: dict, record_dir: Path, target: float, prev_dir: Path | None,
               source_rows: list[dict], track: str = "llm") -> str:
    evals, logs = record["evals"], record["logs"]
    clocks = {s: logs[s]["final_time_s"] for s in sorted(logs)}
    flops = {s: logs[s].get("final_flops") for s in sorted(logs)}
    show_flops = TRACKS[track].get("show_flops", True)   # non-LLM track has no FLOPs co-metric
    flops_hdr, flops_sep = (" FLOPs |", "---|") if show_flops else ("", "")
    lines = ["## Results", "", f"| seed | held-out eval pass@1 | 95% CI | record clock |{flops_hdr}",
             f"|---|---|---|---|{flops_sep}"]
    for s in sorted(evals):
        ev, clock, fl = evals[s], clocks.get(s), flops.get(s)
        hms = fmt_clock(clock) if clock else "—"
        flo = f" {fmt_flops(fl)} |" if show_flops else ""
        lines.append(f"| {s} | {ev['pass_at_1']:.4f} | [{ev['ci_low']:.4f}, {ev['ci_high']:.4f}] "
                     f"| {hms} |{flo}")
    # Single-seed gate: each run independently clears the target via its lower 95% bootstrap CI
    # (no cross-seed averaging — see the leaderboard rules).
    if len(evals) == 1:
        only = evals[sorted(evals)[0]]
        verdict = "CLEARS" if only["ci_low"] > target else "DOES NOT CLEAR"
        summary = (f"**Held-out eval pass@1 {only['pass_at_1']:.4f}, lower 95% CI "
                   f"{only['ci_low']:.4f} vs TARGET {target}: {verdict}.**")
    else:
        all_clear = all(ev["ci_low"] > target for ev in evals.values())
        summary = (f"**Each of {len(evals)} runs vs TARGET {target} by its lower 95% CI: "
                   f"{'ALL CLEAR' if all_clear else 'NOT ALL CLEAR'}.**")
    lines += ["", summary, "",
              "![hero](plots/hero.png)", "",
              "![training](plots/training.png)", "",
              "<details><summary>diagnostic plots</summary>", "",
              "![stability](plots/stability.png)", "",
              "![eval](plots/eval.png)", "",
              "</details>", ""]
    lines += verification_block(record_dir, target)
    lines += source_block(record_dir, source_rows, TRACKS[track]["script"])
    # Config: headline table + diff vs previous record + full dict.
    args = logs[sorted(logs)[0]]["args"]
    lines += ["## Config", "", "| arg | value |", "|---|---|"]
    lines += [f"| `{k}` | `{args[k]}` |" for k in HEADLINE_ARGS if k in args]
    if prev_dir is not None:
        prev_logs = train_log_paths(prev_dir)
        if prev_logs:
            prev_args = parse_train_log(prev_logs[0])["args"]
            diffs = [(k, prev_args.get(k, "—"), args[k]) for k in sorted(args)
                     if k != "run" and str(args[k]) != str(prev_args.get(k))]
            if diffs:
                lines += ["", f"**Changed vs [{prev_dir.name}](../{prev_dir.name}/):**", "",
                          "| arg | before | after |", "|---|---|---|"]
                lines += [f"| `{k}` | `{b}` | `{a}` |" for k, b, a in diffs]
    full = json.dumps({k: str(v) for k, v in sorted(args.items())}, indent=2)
    lines += ["", "<details><summary>full args</summary>", "", "```json", full, "```", "</details>", ""]
    verify_cmds = [cmd.format(record=record_dir.as_posix()) for cmd in TRACKS[track]["verify"]]
    lines += ["## Reproduce", "", "```bash", *TRACKS[track]["reproduce"], *verify_cmds, "```", ""]
    return "\n".join(lines)


def write_readme(record_dir: Path, block: str) -> None:
    readme = record_dir / "README.md"
    auto = f"{AUTO_BEGIN}\n\n{block}\n{AUTO_END}\n"
    if readme.exists():
        text = readme.read_text()
        if AUTO_BEGIN in text and AUTO_END in text:
            pre, rest = text.split(AUTO_BEGIN, 1)
            _, post = rest.split(AUTO_END, 1)
            readme.write_text(pre + auto + post)
            return
        readme.write_text(text.rstrip() + "\n\n" + auto)
        return
    title = record_dir.name
    readme.write_text(
        f"# {title}\n\n## Idea\n\nTODO: describe the recipe — what changed vs the previous "
        f"record, why it should be faster, and anything a reader should know before "
        f"trusting/forking it.\n\n{auto}")


def infer_track(record_dir: Path) -> str:
    """Infer the speedrun track from the normal `cd llm` / `cd non_llm` workflow."""
    paths = [record_dir.resolve(), Path.cwd().resolve()]
    for path in paths:
        parts = set(path.parts)
        if "non_llm" in parts:
            return "non-llm"
        if "llm" in parts:
            return "llm"
    return "llm"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("record_dir", type=Path, nargs="?",
                    help="record dir to report on (omit with --leaderboard)")
    ap.add_argument("--leaderboard", action="store_true",
                    help="regenerate the README world-record figures (assets/*.png) from the leaderboard tables, then exit")
    ap.add_argument("--update-leaderboard", action="store_true",
                    help="after writing the per-record report, insert/refresh this record's row in the "
                         "README world-record table and redraw the figures (Description/Contributors left for you)")
    ap.add_argument("--wandb-runs", default=None,
                    help="comma-separated entity/project/run_id list, one per seed, ordered like the seed files")
    ap.add_argument("--prev", type=Path, default=None, help="previous record dir for the config diff")
    ap.add_argument("--target", type=float, default=None,
                    help="override the selected track's target threshold")
    ap.add_argument("--subtitle", default="", help="optional hero subtitle, e.g. a track label")
    ap.add_argument("--track", choices=["llm", "non-llm"], default=None,
                    help="override the inferred record track")
    args = ap.parse_args()

    if args.leaderboard:
        make_leaderboard()
        return
    if args.record_dir is None:
        ap.error("record_dir is required (or pass --leaderboard)")

    track = args.track or infer_track(args.record_dir)
    target = args.target if args.target is not None else TRACKS[track]["target"]

    set_house_style()
    record = load_record(args.record_dir)
    plots = args.record_dir / "plots"
    plots.mkdir(exist_ok=True)

    seeds = sorted(record["logs"])
    online_frames = None
    if args.wandb_runs:
        online_frames = fetch_wandb_history([r.strip() for r in args.wandb_runs.split(",")])
        if len(online_frames) != len(seeds):
            raise SystemExit(f"got {len(online_frames)} W&B runs for {len(seeds)} seed logs")
    else:
        online_frames = load_metrics_frames(args.record_dir, seeds)
        if online_frames is not None:
            print(f"using metrics_seed*.jsonl for the online train metric ({len(seeds)} seed(s))")

    plot_training(record, online_frames, plots / "training.png", target)
    plot_stability(record, plots / "stability.png")
    plot_eval(record, target, plots / "eval.png")
    plot_hero_card(record, target, plots / "hero.png", online_frames, subtitle=args.subtitle)

    source_rows = ensure_all_source_snapshots(args.record_dir)
    write_readme(args.record_dir,
                 auto_block(record, args.record_dir, target, args.prev, source_rows, track=track))
    print(f"wrote {plots}/*.png (incl. hero.png) and updated {args.record_dir / 'README.md'}")

    if args.update_leaderboard:
        update_leaderboard_row(args.record_dir, track)


if __name__ == "__main__":
    main()
