"""Generate the standard plots + per-record README for a record submission.

Usage:
    python make_record_report.py records/<dir> \
        [--wandb-runs entity/project/id1,entity/project/id2,...] \
        [--prev records/<previous-record-dir>] \
        [--eval-data datasets/sokoban_eval.jsonl]

Artifact-only mode needs nothing beyond the committed record directory
(train_log_seed*.txt + eval_seed*.json): it parses the per-step record-clock lines and
the args attestation straight from the run logs, so any reviewer can regenerate the
plots from the PR alone. --wandb-runs swaps the training panel to the unbiased online
solve-rate metric from W&B history; if your metrics live elsewhere, anything that yields
(step, online_solved_frac) can be adapted — see fetch_wandb_history for the expected shape.

The record README is written with the human-authored sections preserved: everything
between the AUTO markers is regenerated, everything outside them is never touched.
On first run a scaffold with a TODO "Idea" section is created.

Run via:  uv run --with matplotlib --with pandas [--with wandb] python make_record_report.py ...
"""

from __future__ import annotations

import argparse
import glob
import json
import re
import statistics
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

AUTO_BEGIN = "<!-- BEGIN AUTO-GENERATED by make_record_report.py — edits inside will be overwritten -->"
AUTO_END = "<!-- END AUTO-GENERATED -->"
STEP_RE = re.compile(
    r"step:(\d+)/(\d+) record_time:([\d.]+)s step_avg:[\d.]+s reward_mean:([\d.]+) "
    r"solved_frac:([\d.]+) loss:(-?[\d.]+) grad_norm:([\d.]+)"
)
# Key hyperparameters surfaced in the README config table; the full args dict goes in <details>.
HEADLINE_ARGS = [
    "learning_rate", "lr_schedule", "min_lr_frac", "lr_decay_steps", "warmup_steps",
    "cispo_eps", "loss_normalization", "examples_per_step", "num_samples",
    "max_new_tokens", "temperature", "top_p", "max_staleness", "inflight_requests",
    "interruption", "interrupt_answer_tokens", "max_steps", "seed",
]
SEED_COLORS = ["#1f77b4", "#ff7f0e", "#2ca02c"]


def parse_train_log(path: Path) -> dict:
    """Extract the per-step record-clock series and the args attestation from a run log."""
    steps, args_dict = [], None
    for line in path.read_text(errors="replace").splitlines():
        m = STEP_RE.match(line)
        if m:
            steps.append({
                "step": int(m.group(1)), "record_time_s": float(m.group(3)),
                "reward_mean": float(m.group(4)), "solved_frac": float(m.group(5)),
                "loss": float(m.group(6)), "grad_norm": float(m.group(7)),
            })
        elif line.startswith("args: {") and args_dict is None:
            # The attestation prints repr(vars(args)); PosixPath is its only non-literal.
            args_dict = eval(  # noqa: S307 — sandboxed: no builtins, PosixPath -> str
                line[len("args: "):], {"__builtins__": {}}, {"PosixPath": lambda p: p})
        elif line.startswith("final_checkpoint:"):
            m2 = re.search(r"record_time:([\d.]+)s", line)
            if m2 and steps:
                steps[-1]["final_record_time_s"] = float(m2.group(1))
    if not steps:
        raise ValueError(f"{path}: no step lines found")
    df = pd.DataFrame(steps)
    final_time = steps[-1].get("final_record_time_s", df.record_time_s.iloc[-1])
    return {"df": df, "args": args_dict or {}, "final_time_s": final_time}


def load_record(record_dir: Path) -> dict:
    logs, evals = {}, {}
    for p in sorted(record_dir.glob("train_log_seed*.txt")):
        logs[p.stem.replace("train_log_", "")] = parse_train_log(p)
    for p in sorted(record_dir.glob("eval_seed*.json")):
        evals[p.stem.replace("eval_", "").split(".")[0]] = json.loads(p.read_text())
    if not logs or not evals:
        raise SystemExit(f"{record_dir}: need train_log_seed*.txt and eval_seed*.json")
    return {"logs": logs, "evals": evals}


def fetch_wandb_history(run_paths: list[str]) -> list[pd.DataFrame]:
    """One DataFrame per run with step + online-solve columns."""
    import wandb
    api = wandb.Api()
    frames = []
    for rp in run_paths:
        # Full history rather than scan_history(keys=...): keyed scans drop rows missing
        # any requested key, which silently empties the result for sparse metrics.
        df = api.run(rp).history(samples=100_000, pandas=True)
        if "step" not in df.columns:
            raise SystemExit(f"{rp}: no 'step' metric in W&B history")
        frames.append(df[df["step"].notna()].sort_values("step"))
    return frames


def bucket_of(moves: int) -> str:
    return "5-6" if moves <= 6 else "7-8" if moves <= 8 else "9-10" if moves <= 10 else "11+"


def plot_training(record: dict, wandb_frames: list[pd.DataFrame] | None, out: Path) -> None:
    """Solve rate vs step and vs record-clock minutes; W&B's unbiased online metric when available."""
    fig, axes = plt.subplots(1, 2, figsize=(11, 4))
    for i, (seed, log) in enumerate(record["logs"].items()):
        df, c = log["df"], SEED_COLORS[i % len(SEED_COLORS)]
        if wandb_frames is not None:
            w = wandb_frames[i]
            y = w["reward/online_solved_frac_unfiltered"].rolling(5, min_periods=1).mean()
            axes[0].plot(w["step"], y, color=c, alpha=0.9, label=seed)
            t = df.record_time_s.iloc[:len(w)] / 60.0
            axes[1].plot(t, y.iloc[:len(t)], color=c, alpha=0.9, label=seed)
        else:
            y = df.solved_frac.rolling(5, min_periods=1).mean()
            axes[0].plot(df.step, y, color=c, alpha=0.9, label=seed)
            axes[1].plot(df.record_time_s / 60.0, y, color=c, alpha=0.9, label=seed)
    src = "online solve rate (unfiltered)" if wandb_frames is not None else "trained-batch solve rate"
    for ax, xlab in zip(axes, ("training step", "record clock (minutes)")):
        ax.set_xlabel(xlab); ax.set_ylabel(src); ax.grid(alpha=0.3); ax.legend()
    axes[0].set_title("Training curve (5-step rolling mean)")
    axes[1].set_title("The speedrun view: solve rate vs wall clock")
    fig.tight_layout(); fig.savefig(out, dpi=140); plt.close(fig)


def plot_stability(record: dict, out: Path) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(11, 3.6))
    for i, (seed, log) in enumerate(record["logs"].items()):
        df, c = log["df"], SEED_COLORS[i % len(SEED_COLORS)]
        axes[0].plot(df.step, df.grad_norm, color=c, alpha=0.8, label=seed)
        axes[1].plot(df.step, df.loss, color=c, alpha=0.8, label=seed)
    axes[0].set_title("grad norm (pre-clip)"); axes[0].set_yscale("log")
    axes[1].set_title("loss")
    for ax in axes:
        ax.set_xlabel("training step"); ax.grid(alpha=0.3); ax.legend()
    fig.tight_layout(); fig.savefig(out, dpi=140); plt.close(fig)


def plot_eval(record: dict, eval_data: Path, target: float, out: Path) -> None:
    evals = record["evals"]
    fig, axes = plt.subplots(1, 2, figsize=(11, 4))
    # Per-bucket pass@1 (needs the committed eval set for ref_moves).
    if eval_data.exists():
        mv = [json.loads(l)["metadata"]["ref_moves"] for l in eval_data.read_text().splitlines() if l.strip()]
        buckets = ["5-6", "7-8", "9-10", "11+"]
        width = 0.8 / (len(evals) + 1)
        for i, (seed, ev) in enumerate(evals.items()):
            by = {b: [] for b in buckets}
            for idx, frac in enumerate(ev["per_puzzle_solve_frac"]):
                by[bucket_of(mv[idx])].append(frac)
            vals = [statistics.mean(by[b]) for b in buckets]
            axes[0].bar([x + i * width for x in range(len(buckets))], vals, width,
                        color=SEED_COLORS[i % len(SEED_COLORS)], alpha=0.85, label=seed)
        axes[0].set_xticks([x + width for x in range(len(buckets))], buckets)
        axes[0].set_xlabel("reference-solution moves"); axes[0].set_ylabel("pass@1")
        axes[0].set_title("Eval pass@1 by difficulty bucket")
        axes[0].grid(alpha=0.3, axis="y"); axes[0].legend()
    else:
        axes[0].set_axis_off()
        axes[0].text(0.5, 0.5, f"{eval_data} not found — bucket panel skipped", ha="center")
    # pass@k + the target line.
    for i, (seed, ev) in enumerate(evals.items()):
        ks = sorted(int(k) for k in ev["pass_at_k"])
        axes[1].plot(ks, [ev["pass_at_k"][str(k)] for k in ks], "o-",
                     color=SEED_COLORS[i % len(SEED_COLORS)], label=seed)
    axes[1].axhline(target, color="red", ls="--", lw=1, label=f"TARGET {target}")
    axes[1].set_xscale("log", base=2); axes[1].set_xticks(ks, [str(k) for k in ks])
    axes[1].set_xlabel("k"); axes[1].set_ylabel("pass@k"); axes[1].set_title("Eval pass@k")
    axes[1].grid(alpha=0.3); axes[1].legend()
    fig.tight_layout(); fig.savefig(out, dpi=140); plt.close(fig)


def t_test(values: list[float], target: float) -> tuple[float, float | None]:
    """(t, one-sided p) vs target; p needs speedrun.student_t_sf (torch import) — optional."""
    import math
    mean, sd = statistics.mean(values), statistics.stdev(values)
    t = (mean - target) / (sd / math.sqrt(len(values))) if sd > 0 else float("inf")
    try:
        from speedrun import student_t_sf
        return t, student_t_sf(t, len(values) - 1)
    except Exception:
        return t, None


def auto_block(record: dict, record_dir: Path, target: float, prev_dir: Path | None) -> str:
    evals, logs = record["evals"], record["logs"]
    values = [evals[s]["pass_at_1"] for s in sorted(evals)]
    t, p = t_test(values, target)
    clocks = {s: logs[s]["final_time_s"] for s in sorted(logs)}
    lines = ["## Results", "", "| seed | pass@1 | 95% CI | record clock |", "|---|---|---|---|"]
    for s in sorted(evals):
        ev, clock = evals[s], clocks.get(s)
        hms = f"{int(clock // 3600)}:{int(clock % 3600 // 60):02d}:{int(clock % 60):02d}" if clock else "—"
        lines.append(f"| {s} | {ev['pass_at_1']:.4f} | [{ev['ci_low']:.4f}, {ev['ci_high']:.4f}] | {hms} |")
    p_txt = f", one-sided p = {p:.5f}" if p is not None else " (run verify_record.py for the p-value)"
    lines += ["", f"**Mean pass@1 {statistics.mean(values):.4f} ± {statistics.stdev(values):.4f} "
                  f"over {len(values)} seeds vs TARGET {target}: t = {t:.2f}{p_txt}.**", "",
              "![training](plots/training.png)", "", "![stability](plots/stability.png)", "",
              "![eval](plots/eval.png)", ""]
    # Config: headline table + diff vs previous record + full dict.
    args = logs[sorted(logs)[0]]["args"]
    lines += ["## Config", "", "| arg | value |", "|---|---|"]
    lines += [f"| `{k}` | `{args[k]}` |" for k in HEADLINE_ARGS if k in args]
    if prev_dir is not None:
        prev_logs = sorted(prev_dir.glob("train_log_seed*.txt"))
        if prev_logs:
            prev_args = parse_train_log(prev_logs[0])["args"]
            diffs = [(k, prev_args.get(k, "—"), args[k]) for k in sorted(args)
                     if k != "run" and str(args[k]) != str(prev_args.get(k))]
            if diffs:
                lines += ["", f"**Changed vs [{prev_dir.name}](../{prev_dir.name}/):**", "",
                          "| arg | before | after |", "|---|---|---|"]
                lines += [f"| `{k}` | `{b}` | `{a}` |" for k, b, a in diffs]
    full = json.dumps({k: str(v) for k, v in sorted(args.items())}, indent=2)
    lines += ["", "<details><summary>full args</summary>", "", "```json", full, "```", "</details>", ""]
    lines += ["## Reproduce", "", "```bash",
              "MAX_STEPS=100 FINAL_EVAL_K=16 FINAL_EVAL_LIMIT=0 RUN_NAME=<run> modal run --detach modal_app.py",
              f"python verify_record.py records/{record_dir.name}", "```", ""]
    return "\n".join(lines)


def write_readme(record_dir: Path, block: str) -> None:
    readme = record_dir / "README.md"
    auto = f"{AUTO_BEGIN}\n\n{block}\n{AUTO_END}\n"
    if readme.exists():
        text = readme.read_text()
        if AUTO_BEGIN in text and AUTO_END in text:
            pre, rest = text.split(AUTO_BEGIN, 1)
            _, post = rest.split(AUTO_END, 1)
            readme.write_text(pre + auto + post)
            return
        readme.write_text(text.rstrip() + "\n\n" + auto)
        return
    title = record_dir.name
    readme.write_text(
        f"# {title}\n\n## Idea\n\nTODO: describe the recipe — what changed vs the previous "
        f"record, why it should be faster, and anything a reader should know before "
        f"trusting/forking it.\n\n{auto}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("record_dir", type=Path)
    ap.add_argument("--wandb-runs", default=None,
                    help="comma-separated entity/project/run_id list, one per seed, ordered like the seed files")
    ap.add_argument("--prev", type=Path, default=None, help="previous record dir for the config diff")
    ap.add_argument("--eval-data", type=Path, default=Path("datasets/sokoban_eval.jsonl"))
    ap.add_argument("--target", type=float, default=0.50)
    args = ap.parse_args()

    record = load_record(args.record_dir)
    plots = args.record_dir / "plots"
    plots.mkdir(exist_ok=True)

    wandb_frames = None
    if args.wandb_runs:
        wandb_frames = fetch_wandb_history([r.strip() for r in args.wandb_runs.split(",")])
    plot_training(record, wandb_frames, plots / "training.png")
    plot_stability(record, plots / "stability.png")
    plot_eval(record, args.eval_data, args.target, plots / "eval.png")

    write_readme(args.record_dir,
                 auto_block(record, args.record_dir, args.target, args.prev))
    print(f"wrote {plots}/*.png and updated {args.record_dir / 'README.md'}")


if __name__ == "__main__":
    main()
