"""Modal entrypoint for the non-LLM Sokoban speedrun track (PufferLib boxoban + in-file PPO)."""

from __future__ import annotations

import os
import shlex
import subprocess
import sys

import modal

APP_NAME = "sokoban-non-llm"
VOLUME_NAME = "nanochat-rl-hf"          # share the LLM track's volume so records sit side by side
VOLUME_MOUNT_PATH = "/vol"


def _strict_h100_type(raw: str) -> str:
    # Modal's plain H100 request can auto-upgrade to H200; H100! opts out for benchmark runs.
    gpu_type = raw.strip()
    if gpu_type == "H100":
        return "H100!"
    if gpu_type != "H100!":
        raise ValueError(
            "Non-LLM record runs must use Modal gpu='H100!' so they cannot be auto-upgraded. "
            f"Got GPU_TYPE={raw!r}."
        )
    return gpu_type


GPU_TYPE = _strict_h100_type(os.environ.get("GPU_TYPE", "H100!"))
NUM_GPUS = int(os.environ.get("NUM_GPUS", "1"))
GPU_CONFIG = f"{GPU_TYPE}:{NUM_GPUS}"
NVCC_ARCH = os.environ.get("NVCC_ARCH", "sm_90")  # H100.
PUFFERLIB_REPO = "https://github.com/JeanKaddour/PufferLib.git"
PUFFERLIB_REF = "e90b58e"
PUFFERLIB_DIR = "/opt/PufferLib"

app = modal.App(APP_NAME)
volume = modal.Volume.from_name(VOLUME_NAME, create_if_missing=True)

_FORWARD_KEYS = ("WANDB_API_KEY", "WANDB_ENTITY")
_forward = {k: os.environ[k] for k in _FORWARD_KEYS if os.environ.get(k)}
runtime_secrets = [modal.Secret.from_dict(_forward)] if _forward else []

# PufferLib's Boxoban backend is generated by build.sh, not by pyproject.toml. Keep an editable
# clone in the image so the built pufferlib._C extension and resources/boxoban live under the same
# root that speedrun.pufferlib_root() resolves.
_PYLIB = "import nvidia.{m}, os; print(os.path.join(nvidia.{m}.__path__[0], 'lib'))"
_FLOAT_BUILD_PATCH = f"""python - <<'PY'
from pathlib import Path
path = Path({PUFFERLIB_DIR!r}) / "src" / "kernels.cu"
needle = '''inline void cast_dispatch(precision_t* dst, const float* src, int n, cudaStream_t stream) {{
    cast<<<grid_size(n), BLOCK_SIZE, 0, stream>>>(dst, src, n);
}}

'''
guard = "#ifndef PRECISION_FLOAT\\n" + needle + "#endif\\n\\n"
text = path.read_text(encoding="utf-8")
if guard not in text:
    path.write_text(text.replace(needle, guard, 1), encoding="utf-8")
PY"""
image = (
    modal.Image.from_registry("nvidia/cuda:12.6.2-devel-ubuntu22.04", add_python="3.12")
    .apt_install("clang", "libomp-dev", "git", "build-essential", "curl", "ca-certificates", "unzip", "ccache")
    .pip_install("torch==2.9.0", index_url="https://download.pytorch.org/whl/cu126")
    .pip_install("numpy", "rich", "rich_argparse", "pybind11", "scikit-learn", "wandb")
    .env({"OMP_NUM_THREADS": "1", "NVCC_ARCH": NVCC_ARCH})
    .run_commands(
        f"git clone {PUFFERLIB_REPO} {PUFFERLIB_DIR}",
        f"cd {PUFFERLIB_DIR} && git checkout {PUFFERLIB_REF}",
        f"python -m pip install -e {PUFFERLIB_DIR}",
        f"ln -sf libcudnn.so.9 $(python -c \"{_PYLIB.format(m='cudnn')}\")/libcudnn.so",
        f"ln -sf libnccl.so.2 $(python -c \"{_PYLIB.format(m='nccl')}\")/libnccl.so",
        _FLOAT_BUILD_PATCH,
        f"cd {PUFFERLIB_DIR} && NVCC_ARCH={NVCC_ARCH} bash build.sh boxoban --float",
    )
    .add_local_python_source("speedrun")
    .add_local_dir("data", remote_path="/root/data")
)


def _runtime_env() -> dict[str, str]:
    """LD_LIBRARY_PATH must include the pip nvidia wheel lib dirs (cudnn/nccl) so the built _C.so and
    torch resolve their CUDA libs in the launched process."""
    import glob
    import sysconfig

    env = dict(os.environ)
    libs = glob.glob(os.path.join(sysconfig.get_paths()["purelib"], "nvidia", "*", "lib"))
    existing = env.get("LD_LIBRARY_PATH", "")
    env["LD_LIBRARY_PATH"] = ":".join(libs + ([existing] if existing else []))
    return env


def _run(extra_args: list[str]) -> None:
    cmd = [sys.executable, "-u", "-m", "speedrun", "--output-dir", f"{VOLUME_MOUNT_PATH}/outputs",
           *extra_args]
    print(f"Launching: {' '.join(cmd)}", flush=True)
    subprocess.run(cmd, check=True, env=_runtime_env())
    volume.commit()


@app.function(image=image, gpu=GPU_CONFIG, timeout=24 * 60 * 60,
              volumes={VOLUME_MOUNT_PATH: volume}, secrets=runtime_secrets)
def train(run_name: str | None, difficulty: int | None, total_timesteps: int | None,
          holdout_frac: float | None, extra_args: list[str] | None = None) -> None:
    args = []
    if run_name is not None:
        args += ["--run", run_name]
    if difficulty is not None:
        args += ["--difficulty", str(difficulty)]
    if total_timesteps is not None:
        args += ["--total-timesteps", str(total_timesteps)]
    if holdout_frac is not None:
        args += ["--holdout-frac", str(holdout_frac)]
    args += [*(extra_args or [])]
    _run(args)


@app.function(image=image, gpu=GPU_CONFIG, timeout=6 * 60 * 60,
              volumes={VOLUME_MOUNT_PATH: volume}, secrets=runtime_secrets)
def evaluate(checkpoint: str, run_name: str | None, extra_args: list[str] | None = None) -> None:
    args = ["--eval-only", "--eval-checkpoint", checkpoint]
    if run_name is not None:
        args += ["--run", run_name]
    args += [*(extra_args or [])]
    _run(args)


@app.function(image=image, gpu=GPU_CONFIG, timeout=30 * 60, volumes={VOLUME_MOUNT_PATH: volume})
def smoke(run_name: str | None, total_timesteps: int, extra_args: list[str]) -> None:
    # short train (no eval) to measure real-loop SPS on the GPU
    args = ["--no-eval", "--total-timesteps", str(total_timesteps), *extra_args]
    if run_name is not None:
        args = ["--run", run_name, *args]
    _run(args)


@app.local_entrypoint()
def main() -> None:
    run_name = os.environ.get("RUN_NAME")
    difficulty = int(os.environ["DIFFICULTY"]) if os.environ.get("DIFFICULTY") else None
    holdout_frac = float(os.environ["HOLDOUT_FRAC"]) if os.environ.get("HOLDOUT_FRAC") else None
    extra = shlex.split(os.environ.get("EXTRA_ARGS", "")) or None

    # SMOKE: measure H100 speed. Default to the winning config on difficulty 0 (basic = procedural,
    # no big download), 8192 agents — directly comparable to the 3090's 172k env-steps/s.
    cfg_args = ["--difficulty", os.environ.get("DIFFICULTY", "0"),
                "--arch", os.environ.get("ARCH", "sgpm2-mingru"),
                "--num-layers", os.environ.get("NUM_LAYERS", "3"),
                "--hidden-size", os.environ.get("HIDDEN_SIZE", "256"),
                "--num-agents", os.environ.get("NUM_AGENTS", "8192")]
    if os.environ.get("SMOKE"):
        smoke.remote(run_name, int(os.environ.get("SMOKE_STEPS", "60000000")), cfg_args)
        return

    eval_ckpt = os.environ.get("EVAL_CHECKPOINT")
    if eval_ckpt:
        evaluate.remote(eval_ckpt, run_name, extra)
        return

    total = int(os.environ["TOTAL_TIMESTEPS"]) if os.environ.get("TOTAL_TIMESTEPS") else None
    call = train.spawn(run_name, difficulty, total, holdout_frac, extra)
    total_desc = str(total) if total is not None else "RECIPE"
    print(f"Spawned Modal function call: {call.object_id} "
          f"(run={run_name or 'default'}, difficulty={difficulty}, total_timesteps={total_desc}, "
          f"holdout_frac={holdout_frac}, extra_args={extra})", flush=True)
    try:
        print(f"Function call dashboard: {call.get_dashboard_url()}", flush=True)
    except Exception:
        pass
